swagger: '2.0'
info:
  version: 1.0.0
  title: API
  description: ''
  termsOfService: ''
  contact:
    email: null
  license:
    name: null
    url: null
schemes:
  - http
host: null
basePath: null
securityDefinitions: null
security: null
definitions:
  Offer:
    type: object
    properties:
      alias: {}
      append_where_primary_key: {}
      create: {}
      delete: {}
      distinct: {}
      get: {}
      get_or_404: {}
      id: {}
      in_query: {}
      load: {}
      lookup: {}
      none_as_none: {}
      'on': {}
      query: {}
      select: {}
      text: {}
      title: {}
      to_dict: {}
      update: {}
      user_id: {}
tags: []
paths:
  /offer:
    post:
      operationId: get_offer
      summary: Get offer
      consumes:
        - application/json
      produces:
        - null
      parameters: []
      responses:
        '200':
          schema:
            $ref: '#/definitions/Offer'
  /offer/create:
    post:
      operationId: create_offer
      summary: Create offer
      consumes:
        - application/json
      produces:
        - null
      parameters: []
      responses:
        '200':
          schema:
            $ref: '#/definitions/Offer'
